services:
   jobs-postgres:
      image: postgres:latest
      container_name: jobs-postgres
      ports:
         - '6500:5432'
      volumes:
         - jobs_postgres_data:/var/lib/postgresql/data
      env_file:
         - ../.env


volumes:
   jobs_postgres_data:
